#!/usr/bin/env bash
# ==============================================================================
# 10_summary.sh -- Print all credentials and connection info
# ==============================================================================
step "STEP 10/10 -- Deployment summary"

cd "${PROJECT_DIR}"

# Read credentials
MYSQL_ROOT_PASS=$(grep MYSQL_ROOT_PASSWORD .env_sql | cut -d= -f2 | tr -d '"' | tr -d "'")
PUSH_KEY=$(grep PUSH_SECURITY_KEY .env_push | cut -d= -f2 | tr -d '"' | tr -d "'" | cut -c1-32)
SMTP_LOGIN_PORTAL=$(grep SMTP_LOGIN_PORTAL docker-compose.yml | head -1 | awk '{print $2}')
SMTP_LOGIN_SHOP=$(grep SMTP_LOGIN_SHOP docker-compose.yml | head -1 | awk '{print $2}')
PUSH_SUB_PORT=$(grep PUSH_SUB_PORT .env_push_sub | cut -d= -f2 | tr -d '"' | tr -d "'")
PUSH_PUB_PORT=$(grep PUSH_PUB_PORT .env_push_pub | cut -d= -f2 | tr -d '"' | tr -d "'")
REDIS_SESS_DB=1   # PHP system sessions
REDIS_CACHE_DB=0  # Bitrix cache (default)

# Bitrix DB credentials (from .settings.php if present, else .deploy_credentials)
if [[ -f "${FTP_HOME}/bitrix/.settings.php" ]]; then
    BITRIX_DB_USER=$(grep -oP "'login' => '\K[^']*" "${FTP_HOME}/bitrix/.settings.php" | head -1)
    BITRIX_DB_PASS=$(grep -oP "'password' => '\K[^']*" "${FTP_HOME}/bitrix/.settings.php" | head -1)
    BITRIX_DB_NAME=$(grep -oP "'database' => '\K[^']*" "${FTP_HOME}/bitrix/.settings.php" | head -1)
    CRYPTO_KEY=$(grep -oP "'crypto_key' => '\K[^']*" "${FTP_HOME}/bitrix/.settings.php" | head -1)
elif [[ -f "${PROJECT_DIR}/.deploy_credentials" ]]; then
    source "${PROJECT_DIR}/.deploy_credentials"
    CRYPTO_KEY="${BITRIX_CRYPTO_KEY:-}"
else
    BITRIX_DB_USER="bitrix"
    BITRIX_DB_PASS="(see .settings.php or run setup wizard)"
    BITRIX_DB_NAME="bitrix"
    CRYPTO_KEY="(generated by wizard)"
fi

C1="${CYAN}"; C2="${GREEN}"; C3="${YELLOW}"; R="${NC}"

echo
echo -e "${BLUE}╔══════════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║           BITRIX24 STACK -- DEPLOYMENT CREDENTIALS & INFO           ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════════════════╝${NC}"

echo
echo -e "${C1}┌─ SITE ────────────────────────────────────────────────────────────────${R}"
echo -e "  URL          : ${C2}https://${DOMAIN}/${R}"
echo -e "  Admin panel  : ${C2}https://${DOMAIN}/bitrix/admin/${R}"
echo -e "  Install wizard: ${C2}https://${DOMAIN}/bitrix/wizard/${R}"
echo -e "  Server IP    : ${C2}${SERVER_IP}${R}"

echo
echo -e "${C1}┌─ MYSQL (Percona 8.0) ─────────────────────────────────────────────────${R}"
echo -e "  Host         : ${C2}mysql:3306${R}  (Docker alias, from containers)"
echo -e "  Root user    : ${C2}root${R}"
echo -e "  Root password: ${C3}${MYSQL_ROOT_PASS}${R}"
echo -e "  Bitrix DB    : ${C2}${BITRIX_DB_NAME:-bitrix}${R}"
echo -e "  Bitrix user  : ${C2}${BITRIX_DB_USER:-bitrix}${R}"
echo -e "  Bitrix pass  : ${C3}${BITRIX_DB_PASS:-(see .settings.php)}${R}"
echo -e "  Data dir     : /opt/bitrix/volumes/mysql  ->  /var/lib/mysql  (NVMe 250G)"
echo -e "  Tmpdir       : /opt/bitrix/volumes/mysql-tmp  ->  /var/lib/mysql/tmp  (NVMe 20G)"
echo -e "  Config       : ${PROJECT_DIR}/confs/mysql/etc/my.cnf.d/z_bx_custom.cnf"
echo -e "  Buffer pool  : 40 GB  |  max_connections: 300  |  io_capacity: 4000"

echo
echo -e "${C1}┌─ REDIS ────────────────────────────────────────────────────────────────${R}"
echo -e "  Host         : ${C2}redis:6379${R}  (Docker alias)"
echo -e "  Password     : (none)"
echo -e "  DB 0         : Bitrix cache (CacheEngineRedis)"
echo -e "  DB 1         : PHP sessions (session.save_handler=redis)"
echo -e "  maxmemory    : 4 GB  |  policy: allkeys-lru"
echo -e "  Data dir     : /opt/bitrix/volumes/redis  ->  /var/lib/redis  (NVMe 20G)"
echo -e "  Check sessions: docker exec bitrix_redis redis-cli -n 1 DBSIZE"

echo
echo -e "${C1}┌─ OPENSEARCH ───────────────────────────────────────────────────────────${R}"
echo -e "  Host         : ${C2}opensearch:9200${R}  (Docker alias, HTTP, no auth)"
echo -e "  Cluster      : bitrix-cluster  |  node: bitrix-node"
echo -e "  Java heap    : 4 GB"
echo -e "  Data dir     : /opt/bitrix/volumes/opensearch  ->  /var/lib/opensearch  (NVMe 150G)"
echo -e "  Health check : docker exec bitrix_php wget -qO- http://opensearch:9200/_cluster/health"

echo
echo -e "${C1}┌─ PUSH-SERVER ──────────────────────────────────────────────────────────${R}"
echo -e "  Sub (listen) : ${C2}push_sub:${PUSH_SUB_PORT}${R}  ->  /bitrix/sub/"
echo -e "  Pub (send)   : ${C2}push_pub:${PUSH_PUB_PORT}${R}  ->  /bitrix/pub/"
echo -e "  Security key : ${C3}${PUSH_KEY}...${R}  (see .env_push)"
echo -e "  Config file  : ${FTP_HOME}/bitrix/.settings_extra.php"

echo
echo -e "${C1}┌─ EMAIL (Postfix -> smtp.mail.ru) ──────────────────────────────────────${R}"
echo -e "  Portal from  : ${C2}${SMTP_LOGIN_PORTAL:-info@crm.cifroweek.com}${R}  (Bitrix24 CRM)"
echo -e "  Shop from    : ${C2}${SMTP_LOGIN_SHOP:-info@cifroweek.com}${R}  (online shop)"
echo -e "  SMTP relay   : smtp.mail.ru:587 (TLS + SASL, sender-dependent)"
echo -e "  PHP chain    : mail() -> msmtp -> postfix:25 -> smtp.mail.ru"
echo -e "  Mail logs    : docker logs bitrix_postfix --tail 50"
echo -e "  Note: mail.ru requires 'app passwords' (not regular account passwords)"

echo
echo -e "${C1}┌─ SSL CERTIFICATES ─────────────────────────────────────────────────────${R}"
echo -e "  Cert dir     : ${PROJECT_DIR}/data/ssl/"
echo -e "  Domain cert  : ${DOMAIN}.fullchain.cert.pem"
echo -e "  Private key  : ${DOMAIN}.key.pem  (NOT in git)"
echo -e "  Managed by   : bitrix_ssl container (auto-renew)"

echo
echo -e "${C1}┌─ FTP (vsftpd FTPS) ────────────────────────────────────────────────────${R}"
echo -e "  Host:port    : ${C2}${SERVER_IP}:21${R}"
echo -e "  Mode         : Passive  ${SERVER_IP}:21000-21010"
echo -e "  User         : ${C2}${FTP_USER}${R}"
echo -e "  Password     : (set manually: passwd ${FTP_USER})"
echo -e "  Root dir     : ${FTP_HOME}"
echo -e "  TLS          : FTPS (explicit)"

echo
echo -e "${C1}┌─ STORAGE (LVM volumes) ────────────────────────────────────────────────${R}"
echo -e "  ${C2}/opt/bitrix/volumes/${R}  (symlinks to all LVM mount points)"
printf "  %-14s  ->  %-30s  %s\n" "www"        "/mnt/bitrix/www"          "SSD  60G  site files"
printf "  %-14s  ->  %-30s  %s\n" "upload"     "/mnt/bitrix/upload"       "SSD  80G  uploads/photos"
printf "  %-14s  ->  %-30s  %s\n" "cache"      "/mnt/bitrix/cache"        "SSD 120G  Bitrix cache"
printf "  %-14s  ->  %-30s  %s\n" "session"    "/mnt/bitrix/session"      "SSD  10G  PHP sessions"
printf "  %-14s  ->  %-30s  %s\n" "logs"       "/mnt/bitrix/logs"         "SSD  20G  project logs"
printf "  %-14s  ->  %-30s  %s\n" "postfix"    "/var/spool/postfix"       "SSD  10G  mail queue"
printf "  %-14s  ->  %-30s  %s\n" "mysql"      "/var/lib/mysql"           "NVMe 250G MySQL data"
printf "  %-14s  ->  %-30s  %s\n" "mysql-tmp"  "/var/lib/mysql/tmp"       "NVMe  20G MySQL tmpdir"
printf "  %-14s  ->  %-30s  %s\n" "opensearch" "/var/lib/opensearch"      "NVMe 150G search index"
printf "  %-14s  ->  %-30s  %s\n" "redis"      "/var/lib/redis"           "NVMe  20G Redis AOF/RDB"
printf "  %-14s  ->  %-30s  %s\n" "docker"     "/var/lib/docker"          "HDD  150G images/overlay2"
printf "  %-14s  ->  %-30s  %s\n" "backup"     "/var/backup"              "HDD  139G local backups"

echo
echo -e "${C1}┌─ SECURITY ─────────────────────────────────────────────────────────────${R}"
echo -e "  SSH/FTP      : only from ${#TRUSTED_IPS[@]} trusted IPs (firewalld mgmt zone)"
echo -e "  fail2ban     : 5 jails (sshd, vsftpd, nginx-admin, nginx-probe, nginx-limit-req)"
echo -e "  HTTP/HTTPS   : Docker iptables-nft (DOCKER-USER chain for bans)"
echo -e "  SELinux      : Enforcing"

echo
echo -e "${C1}┌─ QUICK COMMANDS ───────────────────────────────────────────────────────${R}"
echo -e "  docker compose ps                         -- container status"
echo -e "  docker compose logs -f --tail 50 mysql    -- MySQL log"
echo -e "  docker compose logs -f --tail 50 postfix  -- mail log"
echo -e "  docker compose restart nginx              -- reload nginx (after PHP restart)"
echo -e "  fail2ban-client status nginx-probe        -- banned IPs"
echo -e "  docker exec bitrix_redis redis-cli -n 0 DBSIZE  -- Bitrix cache keys"
echo -e "  docker exec bitrix_redis redis-cli -n 1 DBSIZE  -- PHP session count"

echo
echo -e "${YELLOW}  SAVE THIS OUTPUT! Store credentials in a password manager.${NC}"
echo -e "${BLUE}══════════════════════════════════════════════════════════════════════${NC}"